### ISSUE TITLE
IntTraits::cbrt implementation computes sqrt

### ISSUE THREAD

**Issue by Emerentius** [tiehuis/int_traits#1]
Title says it all, simple mistake in macro.

Also, as an aside, your readme says:

> We do not perform any optimized functions currently. For example, since we do not need to calculate the fractional part of a square root we can make some potential shortcuts to improve this.

I don't think there is much to be squeezed out. Sqrt is a hardware instruction for floats in modern cpus. My pure-integer implementation in my crate [int_sqrt](https://github.com/Emerentius/int_sqrt) of newton's method takes 20x as long to compute.

**Comment by tiehuis** [comment]
Thanks for that. Will push a fix momentarily. I see that there are a few errors in the warning messages as well that I will correct, too.

That is a good point. We could at least specialize the `log2` function to make use of the `leading_zeros` function when available I suppose.
